### ISSUE TITLE
Support Linux platforms

### ISSUE THREAD

**Issue by StephenHodgson** [microsoft/unitysetup.powershell#155] opened 2019-02-02 06:51 UTC
I know this is documented in the code but I thought I'd go ahead and open this up for tracking.

@jwittner could you add the enhancement and good first issue labels please?

- [ ] Install Linux standalone components
- [ ] Build and run Linux standalone player

**Comment by jwittner** [comment] 2019-08-05 22:42
Closing as duplicate of #41

**Closed by jwittner** 2019-08-05 22:42 UTC
Labels: enhancement, good first issue
