### ISSUE TITLE
Failed to install editor on hosted macOS

### ISSUE THREAD

**Issue by StephenHodgson** [microsoft/unitysetup.powershell#156] opened 2019-02-02 07:13 UTC
[Installing editor for macOS fails with Azure Devops build pipeline](https://dev.azure.com/xrtk/Mixed%20Reality%20Toolkit/_build/results?buildId=42)

```
VERBOSE: GET https://unity3d.com/get-unity/download/archive with 0-byte payload
VERBOSE: received 479779-byte response of content type text/html

At /Users/vsts/.local/share/powershell/Modules/UnitySetup/5.0.107/UnitySetup.psm1:372 char:9
+         throw "Could not find archives for Unity version $Version"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Could not find ...sion 2018.3.4f1:String) [], RuntimeException
+ FullyQualifiedErrorId : Could not find archives for Unity version 2018.3.4f1
 
##[error]PowerShell exited with code '1'.
```

Tested with 5.0.107

**Comment by Ziugy** [comment] 2019-02-04 19:45
Correct. There's an issue finding Unity 2018.3 or higher with `Find-UnitySetupInstaller`. I have this fix with my latest changeset in #126.

Will you be willing to help test that branch? I'm also curious how the solution works on hosted agents.

I expect the only potential issue will be how the hosted machine handles mounting a volume. I implemented this this way to support installing Unity in custom locations. Therefore you may need to elevate `pwsh` with `sudo` when running the install command.

Thinking ahead, if there are issues with volume mounting. Perhaps a flag to skip mounting and just let Unity install to the default volume location on macOS, `/Applications/Unity/`. This is also the same location as Unity's hub. Therefore if you need both this workaround becomes more muddled.

**Comment by awolowiecki720** [comment] 2019-03-19 22:46
@Ziugy question about Test-UnitySetupInstance - unlike gusi it is returning false for me unless I am in the exact path to the editor or i specify that path to pwsh; in which case I obviously know if it's installed since i can look directly at the path. Am i using this as intended or am i missing the point? 
For example, gusi will just list every version installed and the path to it. @jwittner

**Comment by Ziugy** [comment] 2019-03-21 20:31
With the log you posted [here](https://gist.github.com/StephenHodgson/9898dd69e8008278001f87e233233b0d) it seems this issue is now related to volume mounts. Any preferred suggestions on how you would want this handled?

**Comment by StephenHodgson** [comment] 2019-03-24 20:51
I'm not familiar with macOS. Is there something I need to update on my VM? I'm just using the default macOS image provided in Azure Devops.

**Comment by Ziugy** [comment] 2019-03-25 20:01
If you're able to run `pwsh` with `sudo` permissions and test if that works that would be helpful. Otherwise the hosted macs, I assume, do not allow for volumes to be mounted. The latter's work-around will have caveats that I mentioned before: only single Unity install, possible overwrite of Unity hub.

**Comment by StephenHodgson** [comment] 2019-03-26 15:27
> If you're able to run pwsh with sudo permissions and test if that works that would be helpful.

I'm not even sure what that means 😅

**Comment by Ziugy** [comment] 2019-03-26 15:29
`pwsh` = your powershell task
`sudo` = admin privileges

**Comment by StephenHodgson** [comment] 2019-04-01 03:25
Honestly I'm fine with just installing to the default hub path.

I don't know how to test what you're asking for, unfortunately.

**Comment by jwittner** [comment] 2019-04-01 18:06
@Ziugy Anything stopping Stephen from using  `-Destination` and have that put it where he wants it?

**Comment by StephenHodgson** [comment] 2019-04-01 19:19
I just wanna put it in the default hub location, isn't that the default?

**Comment by jwittner** [comment] 2019-04-01 21:23
@Ziugy - Can we simply detect that we're installing to the default location and avoid the mounting? To avoid having to specify a flag.

**Comment by Ziugy** [comment] 2019-04-02 18:01
I'll implement a solution that doesn't require mounting.

**Comment by StephenHodgson** [comment] 2019-04-24 21:51
Here's the latest errors I'm getting
```
ForEach-Object : Index operation failed; the array index evaluated to null.
At /Users/vsts/.local/share/powershell/Modules/UnitySetup/5.1.117/UnitySetup.psm1:893 char:23
+         $Installers | ForEach-Object {
+                       ~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [ForEach-Object], RuntimeException
+ FullyQualifiedErrorId : NullArrayIndex,Microsoft.PowerShell.Commands.ForEachObjectCommand
 
```

**Comment by FejZa** [comment] 2019-07-28 08:46
Issue still exists in 5.1.126

`==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
[command]/usr/local/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/Users/vsts/agent/2.154.3/work/_temp/83e91ea4-e68c-42ce-b310-a1923d804365.ps1'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ForEach-Object : Index operation failed; the array index evaluated to null.
At /Users/vsts/.local/share/powershell/Modules/UnitySetup/5.1.126/UnitySetup.psm1:945 char:23
+         $Installers | ForEach-Object {
+                       ~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [ForEach-Object], RuntimeException
+ FullyQualifiedErrorId : NullArrayIndex,Microsoft.PowerShell.Commands.ForEachObjectCommand`

**Comment by tonysedniov** [comment] 2019-11-27 12:34
Yello. I'm getting similar error on Azure DevOps hosted MacOs 10.14 agent. Any workarounds?

```
2019-11-27T12:14:36.4659880Z ##[section]Starting: Install Unity
2019-11-27T12:14:36.4665390Z ==============================================================================
2019-11-27T12:14:36.4665470Z Task         : PowerShell
2019-11-27T12:14:36.4665530Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2019-11-27T12:14:36.4665580Z Version      : 2.151.2
2019-11-27T12:14:36.4665690Z Author       : Microsoft Corporation
2019-11-27T12:14:36.4665740Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
2019-11-27T12:14:36.4665800Z ==============================================================================
2019-11-27T12:14:36.6171090Z Generating script.
2019-11-27T12:14:36.6201700Z ========================== Starting Command Output ===========================
2019-11-27T12:14:36.6243900Z [command]/usr/local/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/Users/runner/runners/2.160.1/work/_temp/64585378-2e31-4287-82d6-c96f55ce4158.ps1'
2019-11-27T12:14:39.8703990Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 VERBOSE: Creating new sparse bundle disk image for installation.
2019-11-27T12:14:41.0840940Z hdiutil: create failed - No such file or directory
2019-11-27T12:14:41.0866060Z VERBOSE: Mounting sparse bundle disk.
2019-11-27T12:14:41.1866550Z hdiutil: mount failed - No such file or directory
2019-11-27T12:14:41.3549790Z VERBOSE: Downloading https://beta.unity3d.com/download/e0f9cf1b1aee/MacEditorTargetInstaller/UnitySetup-iOS-Support-for-Editor-2019.3.0b12.pkg to /Users/runner/.unitysetup/Installers/Unity-2019.3.0b12/UnitySetup-iOS-Support-for-Editor-2019.3.0b12.pkg
[DOWNLOAD PROGRESS OMITTED]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  VERBOSE: Installing iOS
2019-11-27T12:15:49.1951630Z VERBOSE: 11/27/2019 12:15:49: Installing iOS to /Volumes/UnitySetup/.
2019-11-27T12:15:49.7657710Z installer: Error trying to locate volume at /Volumes/UnitySetup/
2019-11-27T12:15:49.8322480Z Install-UnitySetupPackage : 11/27/2019 12:15:49: Failed with exit code: 1
2019-11-27T12:15:49.8322830Z At /Users/runner/.local/share/powershell/Modules/UnitySetup/5.1.128/UnitySetup.psm1:1035 char:17
2019-11-27T12:15:49.8323260Z + ...             Install-UnitySetupPackage -Package $_ -Destination $packa ...
2019-11-27T12:15:49.8323370Z +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-11-27T12:15:49.8323830Z + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
2019-11-27T12:15:49.8324250Z + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install-UnitySetupPackage
2019-11-27T12:15:49.8324310Z  
2019-11-27T12:15:50.8353230Z ##[error]PowerShell exited with code '1'.
2019-11-27T12:15:50.8363730Z ##[error]PowerShell wrote one or more lines to the standard error stream.
2019-11-27T12:15:50.8365290Z ##[section]Finishing: Install Unity

```

**Comment by K-Ubu** [comment] 2020-04-21 07:43
Hi, I also got the same error with @tonysedniov.
How should I install unity?

Agent: ms hosted macOS-latest
step:
- powershell: |
    Install-UnitySetupInstance -Installers (Find-UnitySetupInstaller -Version '2019.3.10f1' -Components iOS) -Verbose
  displayName: 'Unity component installations.'

Logs:

> VERBOSE: 04/21/2020 07:30:02: Installing iOS to /Volumes/UnitySetup/.
> installer: Error trying to locate volume at /Volumes/UnitySetup/
> Write-Error: /Users/runner/.local/share/powershell/Modules/UnitySetup/5.3.132/UnitySetup.psm1:1068
> Line |
> 1068 |  …             Install-UnitySetupPackage -Package $_ -Destination $packa …
>      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | 04/21/2020 07:30:02: Failed with exit code: 1
> ##[error]PowerShell exited with code '1'.
> Finishing: Unity component installations.

**Comment by jwittner** [comment] 2020-04-21 18:55
@Ziugy - you still using a Mac? Have any work in progress on a solution?

**Comment by cturkdogan** [comment] 2020-04-22 02:26
Is there an update on this issue? Still exists:
2020-04-14T06:59:25.1234950Z [command]/usr/local/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/Users/runner/runners/2.165.2/work/_temp/03d17c52-4ee6-49f1-998b-c43dce151d9e.ps1'
2020-04-14T06:59:30.9677990Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 VERBOSE: Creating new sparse bundle disk image for installation.
2020-04-14T06:59:32.2207410Z hdiutil: create failed - No such file or directory
2020-04-14T06:59:32.2230710Z VERBOSE: Mounting sparse bundle disk.
2020-04-14T06:59:32.3153690Z hdiutil: mount failed - No such file or directory

**Comment by akiojin** [comment] 2020-04-22 11:45
Shouldn't the downloaded package just be mounted, and I just need to specify the editor's path to install it?

**Comment by akiojin** [comment] 2020-04-22 12:51
I tried it on a local MAC environment, but I think the problem is that the Unity package is not installed first. It was possible to install without a problem when I did not specify the part which had made the component to be installed only in iOS, and to put in all.

However, we will try to work with Microsoft-hosted.

PowerShell is described below for your reference.

```
Install-UnitySetupInstance -Installers (Find-UnitySetupInstaller -Version '2019.3.0f1') -Verbose
```

**Comment by akiojin** [comment] 2020-04-22 13:18
It didn't work in a Microsoft-hosted environment.

**Comment by Ziugy** [comment] 2020-04-28 00:22
Hi all, I do not have any work in progress and haven't had a chance to get back around to this.

Here's my notes on the possible work-around I was going to attempt to help address hosted agents. On the plus side these should not require sudo.
> Use `xar` to extract the contents of the `pkg` and then within the contents there's a `pkg.tmp` that you can then use the `tar` command to deploy to a given directory. Caveat is that you will need to know where the contents need to be extracted too.

There's a few links to note that are interesting in solving the macOS package extraction (and improving the windows side too):
- https://public-cdn.cloud.unity3d.com/hub/prod/releases-darwin.json
  - This json describes where to extract content too. (i.e. `"destination": "{UNITY_PATH}/Unity.app/Contents/PlaybackEngines/MacStandaloneSupport"`)
- https://download.unity3d.com/download_unity/ceef2d848e70/unity-osx.ini
  - If we have the version changeset, which we do, you could build this url to pull down extra meta content about the packages. I'm not seeing any command line parameters like in the Windows ini so perhaps not as useful to address this macOS issue. Important to see nonetheless.
- https://download.unity3d.com/download_unity/ceef2d848e70/unity-win.ini
  - To highlight what I'm talking about in the bullet point above, this is the Windows ini that has `cmd="{FILENAME}" /S /D={MODULEDIR}` which will describe the command to run to install the given packages.

**Comment by BattlefieldNoob** [comment] 2020-06-27 15:54
I've found the problem behind "Error trying to locate volume at /Volumes/UnitySetup/" we just need to ensure that the folder .unitysetup exist before creating .sparsebundle file, on Azure Pipelines i've temporary fixed by adding this task
```
task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        mkdir ~/.unitysetup
```
Before `Install-UnitySetupInstance`
I've Also opened this Pull Request #209

**Comment by jwittner** [comment] 2020-07-27 17:38
I've merged this in - can anyone with a Mac verify this issue is resolved?

**Comment by MaxGuernseyIII** [comment] 2020-07-29 02:19
@jwittner I tried the prerelease build on a hosted Mac and I still needed to create ~/.unitysetup to make it work. I don't know if that tells us anything because I don't know if there is a prerelease build with your change in it, yet, or not.

**Comment by MaxGuernseyIII** [comment] 2020-07-29 02:41
@jwittner:

I ensured I had `5.3.136-develop` installed, and got this error:

```
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Located intallers:
iOS: https://beta.unity3d.com/download/2ab9c4179772/MacEditorTargetInstaller/UnitySetup-iOS-Support-for-Editor-2020.1.0f1.pkg
Executing install...
created: /Users/runner/.unitysetup/UnitySetup.sparsebundle
/dev/disk2          	GUID_partition_scheme          	
/dev/disk2s1        	EFI                            	
/dev/disk2s2        	Apple_HFS                      	/Volumes/UnitySetup

**snipped downloading messages**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 installer: Package name is iOSSupport
installer: Installing at base path /Volumes/UnitySetup
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “UnitySetup-iOS-Support-for-Editor-2020.1.0f1.pkg”.)
Write-Error: /Users/runner/.local/share/powershell/Modules/UnitySetup/5.3.136/UnitySetup.psm1:1074
Line |
1074 |  …             Install-UnitySetupPackage -Package $_ -Destination $packa …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 07/29/2020 02:32:29: Failed with exit code: 1

rsync: link_stat "/Volumes/UnitySetup/Applications/Unity/." failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/main.c(996) [sender=2.6.9]
"disk2" ejected.
Starting to compact…
Reclaiming free space…
Finishing compaction…
Reclaimed 1.5 GB out of 31.6 GB possible.
```

I event get that error when I make sure `~/.unitysetup` exists in advance.

**Comment by MaxGuernseyIII** [comment] 2020-07-29 02:50
I think we can chalk that one up to me not using it right. I added "Mac" to the list of components to install and it seems like it might be working, now...

**Comment by MaxGuernseyIII** [comment] 2020-07-29 03:03
Yep, @jwittner. I even deleted the ~/.unitysetup that was previously created and re-ran the setup from a clean-ish workspace and everything seems like it's working, now.

**Comment by jwittner** [comment] 2020-07-29 17:54
Thanks a ton for trying it out @MaxGuernseyIII !

**Closed** 2020-07-29 17:53 UTC
Labels: bug

**Comment by MaxGuernseyIII** [comment] 2020-07-29 20:03
@jwittner The results don't seem to be discoverable, though. That is, installed editors cannot be invoked via `Start-UnityEditor` nor can they be found with `Get-UnitySetupInstance`.

Should we treat that as part of this issue or should I open a new one?

**Comment by MaxGuernseyIII** [comment] 2020-07-29 20:28
The install is definitely there, which means it's probably a different issue. I'll investigate and file as appropriate.
