### ISSUE TITLE
Installs hang when core OS components are missing from Components list.

### ISSUE THREAD

**Issue by StephenHodgson** [microsoft/unitysetup.powershell#162] opened 2019-04-01 05:19 UTC
I'm currently using the following command to download all installer components then installing them, which has been working great.

```PS
Install-UnitySetupInstance -Verbose -Installers ( Find-UnitySetupInstaller -Version $(UnityVersion) -Verbose )
```

But when I attempted to cull that number down to try and get a shorter install time, for some reason hangs indefinitely and never completes.

```PS
Install-UnitySetupInstance -Verbose -Installers ( Find-UnitySetupInstaller -Version $(UnityVersion) -Components 'Windows_IL2CPP', 'UWP_IL2CPP' -Verbose )
```

**Comment by jwittner** [comment] 2019-04-01 18:03
You'll need the 'Windows' component as well for first time installs. You probably had an error box about not being able to find Unity.exe sitting there waiting for your input.

If you can confirm that fixes it maybe we can change this ticket to enhance the installer to test if you haven't included the core installer for the platform, check if it's available, and if not error out.

**Comment by StephenHodgson** [comment] 2019-04-01 19:18
Huh, I was trying to avoid the Windows component all together and just download the il2cpp version.

What is the dependency on the Windows component?

**Comment by jwittner** [comment] 2019-04-01 21:15
Each OS has a core installer that installs Unity.exe. UnitySetup lumps them in with the other components. So you need Windows, not for the ability to build for Windows, but because that's the core installer for the Windows OS that installs Unity.exe. For Mac/Linux, you need the Mac/Linux components or you won't have Unity.exe at all, and the other components will fail to install.

**Comment by jwittner** [comment] 2019-04-01 22:23
@StephenHodgson - can we close this out?

**Comment by StephenHodgson** [comment] 2019-04-02 02:04
Wondering if it's still a bug bc it doesn't automatically install the required component 💭

**Comment by jwittner** [comment] 2019-04-02 02:45
What's the expected behavior here? Detect that it's missing and error out? Or automatically install it?

**Comment by StephenHodgson** [comment] 2019-04-02 03:50
I'd say maybe automatically install it since it's a required component. Thoughts?

**Comment by jwittner** [comment] 2019-04-02 16:03
@Ziugy, @derekfreed, @timGerken - thoughts on this?

**Comment by Ziugy** [comment] 2019-04-02 17:53
At minimum better error handling should be implemented. I would expect that this case is an error instead of assuming the intent. I see this example listed as installing extra components to a current installation.

How we download installers has room for improvement. We should at skip download and install of components already installed. I would still expect that the platform should be specified to be more explicit on actions. If there's concern about always installing `Mac` when you're on `Windows` then perhaps that's something further to discuss.

**Closed** 2022-12-18 16:54 UTC
Labels: bug
